In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Display plots inside the notebook
%matplotlib inline

Making a copy of the dataframe

In [49]:
df = pd.read_csv("../data/netflix_titles.csv")
df_clean=df.copy()

Checking for duplicates

In [50]:
df_clean.duplicated().sum()

np.int64(0)

Checking for null values

In [51]:
df_clean.isnull().sum().sort_values(ascending=False)

director        2634
country          831
cast             825
date_added        10
rating             4
duration           3
show_id            0
type               0
title              0
release_year       0
listed_in          0
description        0
dtype: int64

Normalizing null values and removing null columns

In [52]:
df_clean["director"]=df_clean["director"].fillna("Unknown")
df_clean["cast"]=df_clean["cast"].fillna("Unknown")
df_clean["country"]=df_clean["country"].fillna("Unknown")
df_clean["rating"]=df_clean["rating"].fillna("unknown")

In [53]:
df_clean["date_added"].isnull().sum()
df_clean=df_clean.dropna(subset=["date_added"])

In [54]:
df_clean=df_clean.dropna(subset=["duration"])

In [55]:
df_clean.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

Convertion of the date_added type to Datetime type

In [56]:
df_clean["date_added"]=df_clean["date_added"].str.strip()
df_clean["date_added"]=pd.to_datetime(df_clean["date_added"])

In [57]:
df_clean["date_added"].dtype

dtype('<M8[us]')

Creating new date features`

In [58]:
df_clean["year_added"]=df_clean["date_added"].dt.year

In [59]:
df_clean["month_added"] = df_clean["date_added"].dt.month_name()

In [60]:
df_clean["day_added"] = df_clean["date_added"].dt.day_name()

In [61]:
df_clean.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,day_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,September,Saturday
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,September,Friday
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,September,Friday
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,September,Friday
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,September,Friday

In [62]:
text_columns = [
    "title",
    "director",
    "cast",
    "country",
    "rating",
    "listed_in"
]

for col in text_columns:
    df_clean[col]=df_clean[col].str.strip()

Seperating movies and tv shows durations

In [63]:
df_clean["duration_value"] = df_clean["duration"].str.extract(r"(\d+)").astype(int)

In [64]:
df_clean["duration_unit"] = df_clean["duration"].str.extract(r"([A-Za-z]+)")

In [65]:
df_clean[["duration", "duration_value", "duration_unit"]].head()

    duration  duration_value duration_unit
0     90 min              90           min
1  2 Seasons               2       Seasons
2   1 Season               1        Season
3   1 Season               1        Season
4  2 Seasons               2       Seasons

Reseting the index

In [66]:
df_clean=df_clean.reset_index(drop=True)
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 8794 entries, 0 to 8793
Data columns (total 17 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8794 non-null   str
 1   type            8794 non-null   str
 2   title           8794 non-null   str
 3   director        8794 non-null   str
 4   cast            8794 non-null   str
 5   country         8794 non-null   str
 6   date_added      8794 non-null   datetime64[us]
 7   release_year    8794 non-null   int64
 8   rating          8794 non-null   str
 9   duration        8794 non-null   str
 10  listed_in       8794 non-null   str
 11  description     8794 non-null   str
 12  year_added      8794 non-null   int32
 13  month_added     8794 non-null   str
 14  day_added       8794 non-null   str
 15  duration_value  8794 non-null   int64
 16  duration_unit   8794 non-null   str
dtypes: datetime64[us](1), int32(1), int64(2), str(13)
memory usage: 1.1 MB

Saving the dataset

In [67]:
df_clean.to_csv("../data/netflix_titles_cleaned.csv", index=False)